## Dataset Loading

In [44]:
import pandas as pd
df = pd.read_csv(r"C:\Users\BIT\OneDrive\Desktop\Yash\Projects\Educational BI Framework\Dataset\Raw\student_performance_raw.csv")

## Dataset Inspection

In [45]:
print(df.head(5))
print(df.info())
print(df.isnull().sum())

   StudyHours  Attendance  Resources  Extracurricular  Motivation  Internet  \
0          19          64          1                0           0         1
1          19          64          1                0           0         1
2          19          64          1                0           0         1
3          19          64          1                1           0         1
4          19          64          1                1           0         1

   Gender  Age  LearningStyle  OnlineCourses  Discussions  \
0       0   19              2              8            1
1       0   23              3             16            0
2       0   28              1             19            0
3       0   19              2              8            1
4       0   23              3             16            0

   AssignmentCompletion  ExamScore  EduTech  StressLevel  FinalGrade
0                    59         40        0            1           3
1                    90         66        0            1           2
2                    67         99        1            1           0
3                    59         40        0            1           3
4                    90         66        0            1           2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14003 entries, 0 to 14002
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudyHours            14003 non-null  int64
 1   Attendance            14003 non-null  int64
 2   Resources             14003 non-null  int64
 3   Extracurricular       14003 non-null  int64
 4   Motivation            14003 non-null  int64
 5   Internet              14003 non-null  int64
 6   Gender                14003 non-null  int64
 7   Age                   14003 non-null  int64
 8   LearningStyle         14003 non-null  int64
 9   OnlineCourses         14003 non-null  int64
 10  Discussions           14003 non-null  int64
 11  AssignmentCompletion  14003 non-null  int64
 12  ExamScore             14003 non-null  int64
 13  EduTech               14003 non-null  int64
 14  StressLevel           14003 non-null  int64
 15  FinalGrade            14003 non-null  int64
dtypes: int64(16)
memory usage: 1.7 MB
None
StudyHours              0
Attendance              0
Resources               0
Extracurricular         0
Motivation              0
Internet                0
Gender                  0
Age                     0
LearningStyle           0
OnlineCourses           0
Discussions             0
AssignmentCompletion    0
ExamScore               0
EduTech                 0
StressLevel             0
FinalGrade              0
dtype: int64

## Categorical Value Analysis

In [46]:
categorical_cols = [
    'Extracurricular',
    'Motivation',
    'Internet',
    'Gender',
    'LearningStyle',
    'EduTech',
    'StressLevel',
    'FinalGrade'
]
for col in categorical_cols:
    print("\n===================")
    print(f"\n{col}")
    print(df[col].value_counts())

===================

Extracurricular
Extracurricular
1    8320
0    5683
Name: count, dtype: int64

===================

Motivation
Motivation
1    7098
0    4112
2    2793
Name: count, dtype: int64

===================

Internet
Internet
1    12960
0     1043
Name: count, dtype: int64

===================

Gender
Gender
1    7729
0    6274
Name: count, dtype: int64

===================

LearningStyle
LearningStyle
1    3580
3    3547
2    3500
0    3376
Name: count, dtype: int64

===================

EduTech
EduTech
1    9929
0    4074
Name: count, dtype: int64

===================

StressLevel
StressLevel
2    7098
1    4069
0    2836
Name: count, dtype: int64

===================

FinalGrade
FinalGrade
0    3832
2    3618
1    3310
3    3243
Name: count, dtype: int64

## Data Cleaning

In [47]:
# Dataset Before Cleaning

print(df.shape)

(14003, 16)

In [48]:
# Checking Duplicates

print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 1534

In [49]:
# Removing Duplicates

df = df.drop_duplicates().reset_index(drop = True)
print("Shape after removing the duplicates:", df.shape)
print("Duplicate rows now:",df.duplicated().sum())

Shape after removing the duplicates: (12469, 16)
Duplicate rows now: 0

In [50]:
# Dataset After Cleaning

print(df.shape)

(12469, 16)

## Data Transformation

In [51]:
df['Gender'] = df['Gender'].map({
    0: "Male",
    1: "Female"
})

df['Internet'] = df['Internet'].map({
    0: "No",
    1: "Yes"
})

df['Extracurricular'] = df['Extracurricular'].map({
    0: "No",
    1: "Yes"
})

df['EduTech'] = df['EduTech'].map({
    0: "Low",
    1: "High"
})

df['Motivation'] = df['Motivation'].map({
    0: "Low",
    1: "Medium",
    2: "High"
})

df['StressLevel'] = df['StressLevel'].map({
    0: "Low",
    1: "Medium",
    2: "High"
})

df['LearningStyle'] = df['LearningStyle'].map({
    0: "Visual",
    1: "Auditory",
    2: "Reading/Writing",
    3: "Kinesthetic"
})

df['FinalGrade'] = df['FinalGrade'].map({
    0: "A",
    1: "B",
    2: "C",
    3: "D"
})

In [52]:
print(df.describe())

         StudyHours    Attendance     Resources           Age  OnlineCourses  \
count  12469.000000  12469.000000  12469.000000  12469.000000   12469.000000
mean      20.034405     80.239233      1.101371     23.529152       9.872404
std        6.049485     11.469028      0.711171      3.510956       6.114025
min        5.000000     60.000000      0.000000     18.000000       0.000000
25%       16.000000     70.000000      1.000000     20.000000       5.000000
50%       20.000000     80.000000      1.000000     24.000000      10.000000
75%       24.000000     90.000000      2.000000     27.000000      15.000000
max       44.000000    100.000000      2.000000     29.000000      20.000000

        Discussions  AssignmentCompletion     ExamScore
count  12469.000000          12469.000000  12469.000000
mean       0.606223             74.515358     70.310691
std        0.488606             14.657687     17.696639
min        0.000000             50.000000     40.000000
25%        0.000000             62.000000     55.000000
50%        1.000000             74.000000     70.000000
75%        1.000000             87.000000     86.000000
max        1.000000            100.000000    100.000000

In [53]:
print(df.head())

   StudyHours  Attendance  Resources Extracurricular Motivation Internet  \
0          19          64          1              No        Low      Yes
1          19          64          1              No        Low      Yes
2          19          64          1              No        Low      Yes
3          19          64          1             Yes        Low      Yes
4          19          64          1             Yes        Low      Yes

  Gender  Age    LearningStyle  OnlineCourses  Discussions  \
0   Male   19  Reading/Writing              8            1
1   Male   23      Kinesthetic             16            0
2   Male   28         Auditory             19            0
3   Male   19  Reading/Writing              8            1
4   Male   23      Kinesthetic             16            0

   AssignmentCompletion  ExamScore EduTech StressLevel FinalGrade
0                    59         40     Low      Medium          D
1                    90         66     Low      Medium          C
2                    67         99    High      Medium          A
3                    59         40     Low      Medium          D
4                    90         66     Low      Medium          C

## Feature Engineering

In [54]:
df['PerformanceIndex'] = (
    df['ExamScore'] * 0.5 +
    df['Attendance'] * 0.3 +
    df['AssignmentCompletion'] * 0.2
)

df["EngagementScore"] = (
    df["OnlineCourses"] * 0.6 +
    df["Discussions"] * 0.4
)

In [55]:
print(df[["PerformanceIndex", "EngagementScore"]].head())

   PerformanceIndex  EngagementScore
0              51.0              5.2
1              70.2              9.6
2              82.1             11.4
3              51.0              5.2
4              70.2              9.6

## Risk Categorization

In [56]:
def categorize_risk(score):
    if score >= 80:
        return 'Low Risk'
    if score >= 60:
        return 'Medium Risk'
    else:
        return 'High Risk'
    
df['RiskCategory'] = df['PerformanceIndex'].apply(categorize_risk)

In [57]:
print(df[['PerformanceIndex', 'RiskCategory']].head())

   PerformanceIndex RiskCategory
0              51.0    High Risk
1              70.2  Medium Risk
2              82.1     Low Risk
3              51.0    High Risk
4              70.2  Medium Risk

## Saving Cleaned Dataset

In [58]:
df.to_csv(r"C:\Users\BIT\OneDrive\Desktop\Yash\Projects\Educational BI Framework\Dataset\Cleaned\student_performance_cleaned.csv", index = False)

## MySQL Data Loading

In [59]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root123@localhost:3306/educational_bi_framework"
)

engine.connect()

In [60]:
from sqlalchemy import text

with engine.connect() as conn:
    conn.execute(text("SET FOREIGN_KEY_CHECKS = 0"))
    conn.execute(text("TRUNCATE TABLE fact_performance"))
    conn.execute(text("TRUNCATE TABLE dim_students"))
    conn.execute(text("TRUNCATE TABLE dim_behavior"))
    conn.execute(text("TRUNCATE TABLE dim_environment"))
    conn.execute(text("SET FOREIGN_KEY_CHECKS = 1"))
    conn.commit()

print("All tables truncated successfully")

All tables truncated successfully

In [61]:
students_df = df[[
    "Age",
    "Gender",
    "LearningStyle"
]].copy()

students_df.columns = [
    'age',
    'gender',
    'learning_style'
]

students_df.insert(0, "student_id", range(1, len(students_df) + 1))

students_df.head()

   student_id  age gender   learning_style
0           1   19   Male  Reading/Writing
1           2   23   Male      Kinesthetic
2           3   28   Male         Auditory
3           4   19   Male  Reading/Writing
4           5   23   Male      Kinesthetic

In [62]:
students_df.to_sql(
    name="dim_students",
    con=engine,
    if_exists="append",
    index=False
)

12469

In [63]:
behavior_df = df[[
    "StudyHours",
    "AssignmentCompletion",
    "Discussions",
    "Motivation",
    "StressLevel"
]].copy()

behavior_df.columns = [
    "study_hours",
    "assignment_completion",
    "discussions",
    "motivation",
    "stress_level"
]

behavior_df.head()

   study_hours  assignment_completion  discussions motivation stress_level
0           19                     59            1        Low       Medium
1           19                     90            0        Low       Medium
2           19                     67            0        Low       Medium
3           19                     59            1        Low       Medium
4           19                     90            0        Low       Medium

In [64]:
behavior_df.to_sql(
    name = 'dim_behavior',
    con = engine,
    if_exists = "append",
    index = False
)

12469

In [65]:
environment_df = df[[
    'Internet',
    'OnlineCourses',
    'Extracurricular',
    'EduTech'
]].copy()

environment_df.columns = [
    'internet_access',
    'online_courses',
    'extracurricular',
    'edutech'
]

environment_df.head()

  internet_access  online_courses extracurricular edutech
0             Yes               8              No     Low
1             Yes              16              No     Low
2             Yes              19              No    High
3             Yes               8             Yes     Low
4             Yes              16             Yes     Low

In [66]:
environment_df.to_sql(
    name = 'dim_environment',
    con = engine,
    if_exists = 'append',
    index = False
)

12469

In [67]:
fact_df = df[[
    'Attendance',
    'ExamScore',
    'FinalGrade',
    'PerformanceIndex',
    'EngagementScore',
    'RiskCategory'
]].copy()

fact_df.columns = [
    'attendance',
    'exam_score',
    'final_grade',
    'performance_index',
    'engagement_score',
    'risk_category'
]

fact_df.insert(0, 'environment_id', range(1, len(fact_df) + 1))
fact_df.insert(0, 'behavior_id', range(1, len(fact_df)+ 1))
fact_df.insert(0, 'student_id', range(1, len(fact_df) + 1))

fact_df.head()

,student_id,behavior_id,environment_id,attendance,exam_score,final_grade,performance_index,engagement_score,risk_category
0,1,1,1,64,40,D,51.0,5.2,High Risk
1,2,2,2,64,66,C,70.2,9.6,Medium Risk
2,3,3,3,64,99,A,82.1,11.4,Low Risk
3,4,4,4,64,40,D,51.0,5.2,High Risk
4,5,5,5,64,66,C,70.2,9.6,Medium Risk

In [68]:
fact_df.to_sql(
    name = 'fact_performance',
    con = engine,
    if_exists = 'append',
    index = False
)

12469